name: PR

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install protoc
      run: ./install_protoc.sh
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
    - uses: Swatinem/rust-cache@v2

    - name: Rustfmt
      run: cargo fmt -- --check
    - name: Clippy
      run: |
        cargo --version
        cargo clippy --version
        cargo clippy --all-targets --all-features -- -D warnings
    - name: Run tests
      run: cargo test --verbose

    - name: Ensure protos are up to date
      run: cargo publish --dry-run --all-features -p tracing-actions-otlp
