[workspace]

members = [
    "proto_generator",
    "tracing_actions",
    "tracing_actions_otlp",
]

[workspace.package]
version = "0.3.0"

[workspace.dependencies]
tracing-actions = { path = "tracing_actions", version = "0" }
